### PR TITLE
Ok, I started working on this new feature.

### PR DESCRIPTION
**Pull request by raberik98**

### CODE REVIEW

**Comment by raberik98** [comment]
Can you please review my progress?

**Comment by szilvassy-bence** [comment]
Good job

**Comment by pappdanie1** [comment]
++

**Comment by csabagy00** [comment]
Nice feature you have there!

**Comment by szillas** [comment]
Good progress.

**Comment by HTamasViktoria** [comment]
OK!

**Comment by raberik98** [comment]
Hey, I think I am done with this feature, can you please give me a final review before I merge?

**Comment by szilvassy-bence** [comment]
Ready to go

**Comment by HTamasViktoria** [comment]
Ok, let's merge!

**Comment by pappdanie1** [comment]
Good job

**Comment by csabagy00** [comment]
In my opinion you can merge it.

**Comment by szillas** [comment]
Cool features, merge is a go!

**Pull request merged**
