### PR TITLE
Feature2.0

### PR DESCRIPTION
**Pull request by raberik98**

### CODE REVIEW

**Comment by raberik98** [comment]
Please give one final review before I merge this branch to the main branch

**Comment by szilvassy-bence** [comment]
Good job!:)

**Comment by pappdanie1** [comment]
good job

**Comment by csabagy00** [comment]
Nice work.

**Comment by szillas** [comment]
Merge conflict was resolved, ready to merge!

**Comment by HTamasViktoria** [comment]
Review

**Pull request merged**
