### PR TITLE
feature 3.0 started

### PR DESCRIPTION
**Pull request by szilvassy-bence**
This is for feature 3.0 development

### CODE REVIEW

**Comment by szilvassy-bence** [comment]
Can you please review this feature before I merge?

**Comment by szillas** [comment]
Ready to go.

**Comment by HTamasViktoria** [comment]
OK

**Comment by pappdanie1** [comment]
good job

**Comment by csabagy00** [comment]
You should add it to the main branch.

**Comment by HTamasViktoria** [comment]
Review

**Pull request merged**
